var UPDATE_DATA = 'UPDATE_DATA';
var UPDATE_SEARCH = 'UPDATE_SEARCH';
var UPDATE_SORT = 'UPDATE_SORT';
var UPDATE_FILTER = 'UPDATE_FILTER';
var UPDATE_ERROR_FILTER = 'UPDATE_ERROR_FILTER';
var UPDATE_ERROR_MESSAGE = 'UPDATE_ERROR_MESSAGE';
var UPDATE_SCROLL_TO_INDEX = 'UPDATE_SCROLL_TO_INDEX';
var SELECT_REQUEST = 'SELECT_REQUEST';
var FETCH_FILE = {
  REQUEST: 'FETCH_FILE_REQUEST',
  SUCCESS: 'FETCH_FILE_SUCCESS',
  FAILURE: 'FETCH_FILE_FAILURE'
};
var RESET = 'RESET';

export { FETCH_FILE, RESET, SELECT_REQUEST, UPDATE_DATA, UPDATE_ERROR_FILTER, UPDATE_ERROR_MESSAGE, UPDATE_FILTER, UPDATE_SCROLL_TO_INDEX, UPDATE_SEARCH, UPDATE_SORT };
//# sourceMappingURL=types.js.map
